### ISSUE TITLE
Date() Timezone

### ISSUE THREAD

**Issue by spendres** [denostack/superserial#9]
Have you considered using an ISO Date-Time format to include TZ information, or are you assuming all times are in UTC?

**Comment by wan2land** [comment]
superserial is designed to be unaffected by timezones. The Date type is not affected by the timezone because it is converting to a timestamp.

For example, the following two times are converted to the same string

```js
serialize(new Date("2023-06-01 09:00:00+09:00")) // Asia/Seoul
// 'Date(1685577600000)'

serialize(new Date("2023-06-01 00:00:00+00:00")) // UTC
// 'Date(1685577600000)'
```

This string is then converted by the running JavaScript runtime environment to the following format As a result, it follows the timezone of the runtime environment in which it is executed.

```js
const value = new Date(1685577600000)
value.toLocaleString() // your timezone format
```

**Comment by spendres** [comment]
Exactly what I needed to hear!
